### ISSUE TITLE
Can't find unit singleinstance used by ovoplayer

### ISSUE THREAD

**Issue by KottV** [varianus/ovoplayer#1]
Hi.

I trying to compile ovoplayer from git.
After making components/mcaselli.lpk
I run lazbuild.lpi and got:
/mnt/home2/src/ovoplayer/src/ovoplayer.lpr(36,10) Fatal: (10022) Can't find unit singleinstance used by ovoplayer

fpc 3.0.0
lazarus 1.6.2

What I missed?
Thank you.

**Comment by varianus** [comment]
Hi.

Development of Ovoplayer is actually done on fpc 3.0.2 (current stable release) and Lazarus 1.8 ( now at RC3 release).

Unit singleinstance have been added in fpc 3.0.2.
Ovoplayer could be built on Lazarus 1.6.2  but, due to some changes of forms structure to support highDPI, I'm quite sure that it will crash on startup.

**Comment by KottV** [comment]
thnx, update to 3.0.2 and 1.8.0rc3 helps
I ran into next issue, I think due highDPI exactly
